#!/bin/bash

# رنگ‌ها برای خروجی
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# چک کردن حداقل آرگومان‌ها: ایمیل + حداقل 1 دامنه + target
if [ $# -lt 3 ]; then
  echo -e "${RED}[✗] استفاده نادرست!${NC}"
  echo "مثال درست:"
  echo "  ./setup-ssl.sh mahdi7ab@gmail.com api.tavadentco.ir tavadentco_api:80"
  echo "  ./setup-ssl.sh mahdi7ab@gmail.com api.tavadentco.ir www.tavadentco.ir admin.tavadentco.ir tavadentco_api:80"
  echo ""
  echo "فرمت: ایمیل + دامنه‌ها (یک یا چندتا) + سرویس:پورت"
  exit 1
fi

# پارامتر اول = ایمیل
EMAIL="$1"
shift  # حذف ایمیل از لیست

# پارامتر آخر = proxy target
PROXY_TARGET="${@: -1}"
shift  # حذف target

# بقیه = دامنه‌ها (میانی)
DOMAINS="$@"  # همه باقی‌مانده‌ها دامنه هستند

# تبدیل دامنه‌ها به فرمت مناسب برای Nginx و Certbot
DOMAINS_LIST=$(echo "$DOMAINS" | tr ' ' ',' )
SERVER_NAMES=$(echo "$DOMAINS" | sed 's/^/    server_name /; s/ /;\n    server_name /g' | sed 's/$/;/')

echo -e "${YELLOW}[+] ایمیل:${NC} $EMAIL"
echo -e "${YELLOW}[+] دامنه(ها):${NC} $DOMAINS_LIST"
echo -e "${YELLOW}[+] Proxy Target:${NC} $PROXY_TARGET"
echo -e "${YELLOW}[+] شروع تنظیم SSL...${NC}"

# ساخت دایرکتوری برای گواهی‌ها
mkdir -p /etc/letsencrypt

# تولید گواهی با Certbot (با همه دامنه‌ها)
certbot certonly --standalone \
  -d $(echo "$DOMAINS_LIST" | sed 's/,/ -d /g') \
  --non-interactive --agree-tos --email "$EMAIL" \
  --http-01-port=80 || {
    echo -e "${RED}[✗] خطا در دریافت گواهی SSL${NC}"
    exit 1
}

# مسیر گواهی‌ها (برای اولین دامنه)
MAIN_DOMAIN=$(echo "$DOMAINS" | awk '{print $1}')
CERT_PATH="/etc/letsencrypt/live/$MAIN_DOMAIN"

# ساخت config Nginx
CONFIG_FILE="/etc/nginx/conf.d/$(echo "$MAIN_DOMAIN" | tr '.' '_').conf"

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by setup-ssl.sh - $(date)
upstream backend {
    server $PROXY_TARGET;
}

server {
    listen 80;
    server_name $(echo "$DOMAINS_LIST" | sed 's/,/ /g');
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    $SERVER_NAMES

    ssl_certificate $CERT_PATH/fullchain.pem;
    ssl_certificate_key $CERT_PATH/privkey.pem;
    ssl_trusted_certificate $CERT_PATH/chain.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
    }

    # اختیاری: HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
}
EOF

# تست و ری‌لود Nginx
nginx -t && nginx -s reload
if [ $? -eq 0 ]; then
    echo -e "${GREEN}[✓] SSL با موفقیت برای دامنه(ها) تنظیم شد: $DOMAINS_LIST${NC}"
    echo -e "${GREEN}[✓] کانفیگ ذخیره شد در: $CONFIG_FILE${NC}"
else
    echo -e "${RED}[✗] خطا در Nginx config${NC}"
    exit 1
fi

# تنظیم Cron برای renew خودکار (یکبار)
(crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet && nginx -s reload") | crontab -
echo -e "${GREEN}[✓] Cron برای renew خودکار SSL تنظیم شد${NC}"
