#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# چک کردن حداقل ۳ آرگومان
if [ $# -lt 3 ]; then
  echo -e "${RED}[✗] استفاده نادرست!${NC}"
  echo "مثال:"
  echo "  ./setup-ssl.sh email domain1 [domain2 ...] container:port"
  echo ""
  echo "  ./setup-ssl.sh mahdi7ab@gmail.com api.tavadentco.ir tavadentco_api:80"
  echo "  ./setup-ssl.sh mahdi7ab@gmail.com api.tavadentco.ir admin.tavadentco.ir tavadentco_api:80"
  exit 1
fi

# 1. ایمیل
EMAIL="$1"
shift

# 2. آخرین پارامتر = proxy target (باید شامل : باشه)
PROXY_TARGET="${!#}"  # آخرین آرگومان

# چک کن که target شامل : باشه (مثل container:port)
if [[ ! "$PROXY_TARGET" =~ .*:.* ]]; then
  echo -e "${RED}[✗] Proxy target نامعتبر! باید فرمت container:port باشه${NC}"
  echo "مثال: tavadentco_api:80"
  exit 1
fi

# 3. همه پارامترهای میانی = دامنه‌ها
DOMAINS="${@:1:$#-1}"  # از 1 تا قبل از آخر

# چک کن حداقل یک دامنه باشه
if [ -z "$DOMAINS" ]; then
  echo -e "${RED}[✗] حداقل یک دامنه لازم است!${NC}"
  exit 1
fi

# تبدیل دامنه‌ها به لیست
DOMAINS_LIST=$(echo "$DOMAINS" | tr ' ' ',')
SERVER_NAMES=$(echo "$DOMAINS" | sed 's/^/    server_name /; s/ /;\n    server_name /g' | sed 's/$/;/')

echo -e "${YELLOW}[+] ایمیل:${NC} $EMAIL"
echo -e "${YELLOW}[+] دامنه(ها):${NC} $DOMAINS_LIST"
echo -e "${YELLOW}[+] Proxy Target:${NC} $PROXY_TARGET"
echo -e "${YELLOW}[+] شروع تنظیم SSL...${NC}"

# ساخت دایرکتوری
mkdir -p /etc/letsencrypt

# دریافت گواهی
certbot certonly --standalone \
  -d $(echo "$DOMAINS_LIST" | sed 's/,/ -d /g') \
  --non-interactive --agree-tos --email "$EMAIL" \
  --http-01-port=80 || {
    echo -e "${RED}[✗] خطا در دریافت گواهی SSL${NC}"
    echo "لاگ: /var/log/letsencrypt/letsencrypt.log"
    exit 1
}

# اولین دامنه برای مسیر گواهی
MAIN_DOMAIN=$(echo "$DOMAINS" | awk '{print $1}')
CERT_PATH="/etc/letsencrypt/live/$MAIN_DOMAIN"

# ساخت config
CONFIG_FILE="/etc/nginx/conf.d/${MAIN_DOMAIN//./_}.conf"

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by setup-ssl.sh - $(date)
upstream backend {
    server $PROXY_TARGET;
}

server {
    listen 80;
    server_name $(echo "$DOMAINS_LIST" | sed 's/,/ /g');
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
$SERVER_NAMES

    ssl_certificate $CERT_PATH/fullchain.pem;
    ssl_certificate_key $CERT_PATH/privkey.pem;
    ssl_trusted_certificate $CERT_PATH/chain.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
}
EOF

# تست و ری‌لود Nginx
if nginx -t && nginx -s reload; then
    echo -e "${GREEN}[✓] SSL با موفقیت تنظیم شد برای: $DOMAINS_LIST${NC}"
    echo -e "${GREEN}[✓] کانفیگ ذخیره شد: $CONFIG_FILE${NC}"
else
    echo -e "${RED}[✗] خطا در تنظیمات Nginx${NC}"
    exit 1
fi

# Cron برای renew
(crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet && nginx -s reload") | crontab -
echo -e "${GREEN}[✓] Cron برای renew خودکار تنظیم شد${NC}"
